---
- name: installing tinyproxy 
  apt:
    name: tinyproxy
    state: present
    update_cache: yes
    cache_valid_time: "3600"

- name: copy tinyproxy config file
  template:
    src: templates/tinyproxy/tinyproxy.conf
    dest: /etc/tinyproxy/tinyproxy.conf
  notify:
    - restarting tinyproxy